[workspace]
members = [
  "contracts",
  "packages/achievement",
  "packages/quest",
  "packages/starterpack",
  "packages/collection",
  "packages/controller",
  "packages/leaderboard",
  "packages/orderbook",
  "packages/provider",
  "packages/registry",
  "packages/social",
  "packages/models",
]
description = "Arcade packages"
homepage = "https://github.com/cartridge-gg/arcade/"
cairo-version = "2.13.1"

[workspace.package]
version = "0.0.0"
edition = "2024_07"
cairo-version = "2.13.1"

[workspace.dependencies]
dojo = "1.8.0"
dojo_cairo_test = "1.8.0"
graffiti = { git = "https://github.com/bal7hazar/graffiti.git", rev = "e8b0854" }
openzeppelin = "2.0.0"
starknet = "2.13.1"
cairo_test = "2.13.1"

[workspace.tool.fmt]
sort-module-level-items = true

[profile.sepolia]
[profile.mainnet]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]
