[workspace]
members = [
    "packages/controller",
    "packages/provider",
    "packages/registry",
    "packages/society",
    "packages/achievement",
]
description = "Dojo achievement library"
homepage = "https://github.com/cartridge-gg/arcade/"
cairo-version = "2.8.4"

[workspace.package]
version = "0.0.0"

[workspace.dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.5" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.5" }
starknet = "2.8.4"
cairo_test = "2.8.4"

[workspace.tool.fmt]
sort-module-level-items = true
