[workspace]
members = [
    "packages/collection",
    "packages/controller",
    "packages/provider",
    "packages/registry",
    "packages/social",
    "packages/achievement",
]
description = "Dojo achievement library"
homepage = "https://github.com/cartridge-gg/arcade/"
cairo-version = "2.10.1"

[workspace.package]
version = "0.0.0"
edition = "2024_07"

[workspace.dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
graffiti = { git = "https://github.com/rsodre/graffiti.git", rev = "url" }
starknet = "2.10.1"
cairo_test = "2.10.1"

[workspace.tool.fmt]
sort-module-level-items = true
