[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/slot/deployment/abis/dojo-world.json"
address = "0x260c368e1e2d671de961823eae4c3291e418322cbb6355efd6288c70410ec1e"
transaction_hash = "0x33cc9fe84cee259baec8b7e5e07ac87b62878c69e78e6e24ee84abb42869b36"
block_number = 3
seed = "bushido"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "slot"
rpc_url = "https://api.cartridge.gg/x/bushido/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x53ae976bc0d763ff1088bc761d4654445191bd181de7782ae0b34a7f083f23b"
class_hash = "0x4536555d649bee5c56a0c2a8e2a4ff21c9ab110f0e43099b003b0d09ed13876"
original_class_hash = "0x4536555d649bee5c56a0c2a8e2a4ff21c9ab110f0e43099b003b0d09ed13876"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slot/deployment/abis/contracts/game_center-Actions-38eede8c.json"
reads = []
writes = [
    "game_center-Game",
    "game_center-Achievement",
]
init_calldata = []
tag = "game_center-Actions"
systems = [
    "register_game",
    "update_game",
    "register_achievement",
    "update_achievement",
]
manifest_name = "game_center-Actions-38eede8c"

[[models]]
kind = "DojoModel"
class_hash = "0x1063f6e20ee5acfa2fc12e68a712c47495ea7af53629e5c7183eac45dd91a42"
original_class_hash = "0x1063f6e20ee5acfa2fc12e68a712c47495ea7af53629e5c7183eac45dd91a42"
abi = "manifests/slot/deployment/abis/models/game_center-Achievement-2d85ca77.json"
tag = "game_center-Achievement"
qualified_path = "bushido::models::index::achievement"
manifest_name = "game_center-Achievement-2d85ca77"

[[models.members]]
name = "world"
type = "felt252"
key = true

[[models.members]]
name = "namespace"
type = "felt252"
key = true

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "points"
type = "u16"
key = false

[[models.members]]
name = "whitelisted"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4672551c0438cfa22f2e0e295fae45f5ce8548db4b282d666b74db298b42d1b"
original_class_hash = "0x4672551c0438cfa22f2e0e295fae45f5ce8548db4b282d666b74db298b42d1b"
abi = "manifests/slot/deployment/abis/models/game_center-AchievementCompletion-16a107b5.json"
tag = "game_center-AchievementCompletion"
qualified_path = "bushido::events::index::achievement_completion"
manifest_name = "game_center-AchievementCompletion-16a107b5"

[[models.members]]
name = "world"
type = "felt252"
key = true

[[models.members]]
name = "namespace"
type = "felt252"
key = true

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "progress"
type = "u8"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x41e2c85b555c1e7cc3dcfdaa1c614e4199ea76326928f9fb2d1beaf73418233"
original_class_hash = "0x41e2c85b555c1e7cc3dcfdaa1c614e4199ea76326928f9fb2d1beaf73418233"
abi = "manifests/slot/deployment/abis/models/game_center-AchievementCreation-604e47bb.json"
tag = "game_center-AchievementCreation"
qualified_path = "bushido::events::index::achievement_creation"
manifest_name = "game_center-AchievementCreation-604e47bb"

[[models.members]]
name = "world"
type = "felt252"
key = true

[[models.members]]
name = "namespace"
type = "felt252"
key = true

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "points"
type = "u16"
key = false

[[models.members]]
name = "title"
type = "ByteArray"
key = false

[[models.members]]
name = "description"
type = "ByteArray"
key = false

[[models.members]]
name = "image_uri"
type = "ByteArray"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7877078cee53c30cdfc20402194db687cef0a0e178517ea125632dd0b6f548"
original_class_hash = "0x7877078cee53c30cdfc20402194db687cef0a0e178517ea125632dd0b6f548"
abi = "manifests/slot/deployment/abis/models/game_center-Game-6a4ff15e.json"
tag = "game_center-Game"
qualified_path = "bushido::models::index::game"
manifest_name = "game_center-Game-6a4ff15e"

[[models.members]]
name = "world"
type = "felt252"
key = true

[[models.members]]
name = "namespace"
type = "felt252"
key = true

[[models.members]]
name = "total_points"
type = "u16"
key = false

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "description"
type = "ByteArray"
key = false

[[models.members]]
name = "whitelisted"
type = "bool"
key = false

[[models.members]]
name = "torii_url"
type = "ByteArray"
key = false

[[models.members]]
name = "image_uri"
type = "ByteArray"
key = false
