[package]
cairo-version = "=2.7.0"
name = "quest"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build --typescript && sozo migrate plan && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.14" }
# openzeppelin = "0.15.1"

[lib]
