[package]
name = "orderbook"
version.workspace = true
edition.workspace = true

[dependencies]
models = { path = "../models" }
dojo.workspace = true
openzeppelin.workspace = true
starknet.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[lib]

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "models::rbac::models::index::m_Moderator",
]
