[package]
name = "social"
version.workspace = true
edition.workspace = true

[dependencies]
registry = { path = "../registry" }
dojo.workspace = true
starknet.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[lib]
