[package]
name = "achievement"
version.workspace = true
edition.workspace = true

[dependencies]
dojo.workspace = true
starknet.workspace = true
graffiti.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[lib]

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
