[world]
name = "Cartridge World"
description = "Cartridge World"
website = "https://github.com/dojoengine/dojo-starter"
seed = "arcade"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "ARCADE"

[init_call_args]
"ARCADE-Registry" = [
    "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819",
]

[writers]
"ARCADE" = ["ARCADE-Registry", "ARCADE-Slot", "ARCADE-Society", "ARCADE-Wallet"]

[env]
rpc_url = "https://api.cartridge.gg/x/arcade/katana"
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"
ipfs_config.url = "https://ipfs.infura.io:5001"
ipfs_config.username = "2EBrzr7ZASQZKH32sl2xWauXPSA"
ipfs_config.password = "12290b883db9138a8ae3363b6739d220"
