[package]
cairo-version = "2.8.4"
name = "arcade"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build --typescript && sozo migrate plan && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.1.1" }
achievement = { path = ".." }
controller = { path = ".." }
provider = { path = ".." }
registry = { path = ".." }
social = { path = ".." }
starknet = "2.8.4"
cairo_test = "2.8.4"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.1.1" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyPinning",
    "controller::models::index::m_Account",
    "controller::models::index::m_Controller",
    "controller::models::index::m_Signer",
    "provider::models::index::m_Deployment",
    "provider::models::index::m_Factory",
    "provider::models::index::m_Team",
    "provider::models::index::m_Teammate",
    "registry::models::index::m_Access",
    "registry::models::index::m_Achievement",
    "registry::models::index::m_Game",
    "social::models::index::m_Alliance",
    "social::models::index::m_Guild",
    "social::models::index::m_Member",
    "social::events::index::e_Follow",
]

[profile.slot]
[profile.sepolia]
[profile.mainnet]
