[package]
cairo-version.workspace = true
edition.workspace = true
name = "arcade"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[dependencies]
openzeppelin.workspace = true
dojo.workspace = true
starknet.workspace = true
achievement = { path = ".." }
starterpack = { path = ".." }
collection = { path = ".." }
controller = { path = ".." }
models = { path = ".." }
orderbook = { path = ".." }
provider = { path = ".." }
registry = { path = ".." }
social = { path = ".." }

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyPinning",
    "controller::models::index::m_Account",
    "controller::models::index::m_Controller",
    "controller::models::index::m_Signer",
    "orderbook::models::index::m_Book",
    "orderbook::models::index::m_Order",
    "orderbook::models::index::m_MetadataAttribute",
    "orderbook::events::index::e_Listing",
    "orderbook::events::index::e_Offer",
    "orderbook::events::index::e_Sale",
    "provider::models::index::m_Deployment",
    "provider::models::index::m_Factory",
    "provider::models::index::m_Team",
    "provider::models::index::m_Teammate",
    "registry::models::index::m_Access",
    "registry::models::index::m_Collection",
    "registry::models::index::m_CollectionEdition",
    "registry::models::index::m_Game",
    "registry::models::index::m_Edition",
    "registry::models::index::m_Unicity",
    "social::models::index::m_Alliance",
    "social::models::index::m_Guild",
    "social::models::index::m_Member",
    "social::events::index::e_Follow",
    "starterpack::models::index::m_Config",
    "starterpack::models::index::m_Starterpack",
    "starterpack::models::index::m_Issuance",
    "starterpack::models::index::m_ReferralReward",
    "starterpack::models::index::m_GroupReward",
    "starterpack::events::index::e_StarterpackRegistered",
    "starterpack::events::index::e_StarterpackUpdated",
    "starterpack::events::index::e_StarterpackIssued",
    "starterpack::events::index::e_StarterpackPaused",
    "starterpack::events::index::e_StarterpackResumed",
    "models::rbac::models::index::m_Moderator",
]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]
