[package]
cairo-version = "2.8.4"
name = "game_center"
version = "0.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build --typescript && sozo migrate plan && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.3" }
arcade_registry = { path = ".." }
starknet = "2.8.4"
cairo_test = "2.8.4"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.3" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "arcade_registry::models::index::m_Game",
    "arcade_registry::models::index::m_Achievement",
]

[profile.slot]
