# db_dir = "./torii-db"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x389e47f34690ea699218305cc28cc910028533d61d27773e1db20e0b78e7b65"

[indexing]
events_chunk_size = 1024
blocks_chunk_size = 1024
pending = true
polling_interval = 500
max_concurrent_tasks = 100
world_block = 1086641
contracts = []

[events]
raw = true
historical = ["ARCADE-TrophyProgression"]
