kind = "DojoModel"
class_hash = "0x7877078cee53c30cdfc20402194db687cef0a0e178517ea125632dd0b6f548"
original_class_hash = "0x7877078cee53c30cdfc20402194db687cef0a0e178517ea125632dd0b6f548"
abi = "manifests/slot/base/abis/models/game_center-Game-6a4ff15e.json"
tag = "game_center-Game"
qualified_path = "bushido::models::index::game"
manifest_name = "game_center-Game-6a4ff15e"

[[members]]
name = "world"
type = "felt252"
key = true

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "total_points"
type = "u16"
key = false

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "description"
type = "ByteArray"
key = false

[[members]]
name = "whitelisted"
type = "bool"
key = false

[[members]]
name = "torii_url"
type = "ByteArray"
key = false

[[members]]
name = "image_uri"
type = "ByteArray"
key = false
