kind = "DojoModel"
class_hash = "0x41e2c85b555c1e7cc3dcfdaa1c614e4199ea76326928f9fb2d1beaf73418233"
original_class_hash = "0x41e2c85b555c1e7cc3dcfdaa1c614e4199ea76326928f9fb2d1beaf73418233"
abi = "manifests/slot/base/abis/models/game_center-AchievementCreation-604e47bb.json"
tag = "game_center-AchievementCreation"
qualified_path = "bushido::events::index::achievement_creation"
manifest_name = "game_center-AchievementCreation-604e47bb"

[[members]]
name = "world"
type = "felt252"
key = true

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "points"
type = "u16"
key = false

[[members]]
name = "title"
type = "ByteArray"
key = false

[[members]]
name = "description"
type = "ByteArray"
key = false

[[members]]
name = "image_uri"
type = "ByteArray"
key = false

[[members]]
name = "time"
type = "u64"
key = false
