kind = "DojoModel"
class_hash = "0x4672551c0438cfa22f2e0e295fae45f5ce8548db4b282d666b74db298b42d1b"
original_class_hash = "0x4672551c0438cfa22f2e0e295fae45f5ce8548db4b282d666b74db298b42d1b"
abi = "manifests/slot/base/abis/models/game_center-AchievementCompletion-16a107b5.json"
tag = "game_center-AchievementCompletion"
qualified_path = "bushido::events::index::achievement_completion"
manifest_name = "game_center-AchievementCompletion-16a107b5"

[[members]]
name = "world"
type = "felt252"
key = true

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "progress"
type = "u8"
key = false

[[members]]
name = "time"
type = "u64"
key = false
