kind = "DojoModel"
class_hash = "0x1063f6e20ee5acfa2fc12e68a712c47495ea7af53629e5c7183eac45dd91a42"
original_class_hash = "0x1063f6e20ee5acfa2fc12e68a712c47495ea7af53629e5c7183eac45dd91a42"
abi = "manifests/slot/base/abis/models/game_center-Achievement-2d85ca77.json"
tag = "game_center-Achievement"
qualified_path = "bushido::models::index::achievement"
manifest_name = "game_center-Achievement-2d85ca77"

[[members]]
name = "world"
type = "felt252"
key = true

[[members]]
name = "namespace"
type = "felt252"
key = true

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "points"
type = "u16"
key = false

[[members]]
name = "whitelisted"
type = "bool"
key = false
