world_address = "0x04479801e8674c839115bc6270b9bde0d3288cc974cc8c3c03e615c44038c0ce"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[indexing]
allowed_origins = ["*"]
pending = true
transactions = true

contracts = [
    # "ERC20:0x049D36570D4e46f48e99674bd3fcc84644DdD6b96F7C741B1562B82f9e004dC7", # ETH
    "ERC20:0x2ab526354a39e7f5d272f327fa94e757df3688188d4a92c6dc3623ab79894e2",  # SLAY
    "ERC20:0x040E81cfeB176BFDbc5047BBC55eb471CFAb20a6B221f38d8fDa134E1bFFFca4", # DOG
    "ERC20:0x1e70aedffd376afe33cebdf51ed5365131dccb2a5b2cb36d02b785442912b9b",  # SOL
    "ERC20:0x3b405a98c9e795d427fe82cdeeeed803f221b52471e3a757574a2b4180793ee",  # BROTHER
    # "ERC20:0x0124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49", # LORDS
    # "ERC20:0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK
    "ERC20:0x075afe6402ad5a5c20dd25e10ec3b3986acaa647b77e4ae24b0cbc9a54a27a87", # EKUBO
    "ERC20:0x49201f03a0f0a9e70e28dcd74cbf44931174dbe3cc4b2ff488898339959e559",  # PAL
    "ERC20:0x03fe2b97c1fd336e750087d68b9b867997fd64a2661ff3ca5a7c771641e8e7ac", # BTC
    "ERC20:0x781bddf077f25a53411d567093f63f9a839ec9e6bc4d99d9240cf742b98b0e8",  # BONK
    "ERC20:0x102d5e124c51b936ee87302e0f938165aec96fb6c2027ae7f3a5ed46c77573b",  # SISTER
    "ERC20:0x4fcaf2a7b4a072fe57c59beee807322d34ed65000d78611c909a46fead07fb1",  # DREAMS
    # "ERC20:0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8", # USDC
    "ERC20:0x00acc2fa3bb7f6a6726c14d9e142d51fe3984dbfa32b5907e1e76425177875e2", # SCHIZO
]
