rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[indexing]
allowed_origins = ["*"]
polling_interval = 500
max_concurrent_tasks = 100
pending = true
transactions = false
contracts = [
  "ERC20:0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", # ETH
  "ERC20:0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK
  "ERC20:0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8", # USDC.e
  "ERC20:0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8", # USDT
  "ERC20:0x0124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49", # LORDS
  "ERC20:0x033068f6539f8e6e6b131e6b2b814e6c34a5224bc66947c47dab9dfee93b35fb", # USDC
  "ERC20:0x00da114221cb83fa859dbdb4c44beeaa0bb37c7537ad5ae66fe5e0efd20e6eb3", # DAI
  "ERC20:0x03fe2b97c1fd336e750087d68b9b867997fd64a2661ff3ca5a7c771641e8e7ac", # BTC
]
