rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[indexing]
allowed_origins = ["*"]
polling_interval = 500
max_concurrent_tasks = 100
pending = true
transactions = false
contracts = [
  "ERC20:0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", # ETH
  "ERC20:0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK
  "ERC20:0x053b40a647cedfca6ca84f542a0fe36736031905a9639a7f19a3c1e66bfd5080", # USDC.e
  "ERC20:0x0512feac6339ff7889822cb5aa2a86c848e9d392bb0e3e237c008674feed8343", # USDC
]
